set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME iOS)
set(VCPKG_OSX_DEPLOYMENT_TARGET 15.0)
set(VCPKG_BUILD_TYPE release)
execute_process(COMMAND xcodebuild -version -sdk iphonesimulator Path
  OUTPUT_VARIABLE VCPKG_OSX_SYSROOT
  ERROR_QUIET
  OUTPUT_STRIP_TRAILING_WHITESPACE)
